# Generated by Django 6.0.1 on 2026-02-06 16:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('staff_id', models.CharField(max_length=20, unique=True)),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('role', models.CharField(choices=[('ADMIN', 'Administrator'), ('TEACHER', 'Teacher'), ('ACCOUNTANT', 'Accountant'), ('LIBRARIAN', 'Librarian'), ('TRANSPORT', 'Transport Manager'), ('OTHER', 'Other Support Staff')], default='TEACHER', max_length=20)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone', models.CharField(max_length=20)),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], max_length=1)),
                ('date_of_birth', models.DateField()),
                ('joining_date', models.DateField()),
                ('is_active', models.BooleanField(default=True)),
                ('qualification', models.CharField(help_text='e.g. B.Ed, M.Sc', max_length=100)),
                ('experience_years', models.PositiveIntegerField(default=0)),
                ('address', models.TextField()),
                ('base_salary', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Staff Members',
            },
        ),
    ]
