# Generated by Django 6.0.1 on 2026-02-07 05:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academics', '0002_academicyear_section_capacity'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdmissionApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('date_of_birth', models.DateField()),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], max_length=1)),
                ('email', models.EmailField(help_text="Parent's Email Address", max_length=254)),
                ('parent_phone', models.CharField(max_length=15, verbose_name='Parent Phone Number')),
                ('address', models.TextField(blank=True)),
                ('previous_school', models.CharField(blank=True, max_length=200)),
                ('date_applied', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('pending', 'Pending Review'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=10)),
                ('notes', models.TextField(blank=True, help_text='Internal staff notes')),
                ('grade_applying_for', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academics.grade', verbose_name='Applying for Grade')),
            ],
        ),
    ]
